{
  imports = [
    ./boot.nix
    ./docker.nix
    ./graphics.nix
    ./greetd.nix
    ./home-manager.nix
    ./hyprland.nix
    ./networking.nix
    ./nix.nix
    ./openssh.nix
    ./pipewire.nix
    ./security.nix
    ./sops.nix
    ./stylix.nix
    ./sudo.nix
    ./syncthing.nix
    ./time.nix
    ./tools.nix
    ./zerotier.nix
  ];
}
