apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webdav-books-pvc
  namespace: webdav
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 200Gi
  volumeName: webdav-books-pv
