keys:
  - &super age12ud73504ccl26mrrqncsj204cyv0k2y7tepc64qerqts8xywja0qrn8uwq

  - &hosts
    - &desktop age14lex0cntf4svu3j5j6fe95sh3dlqgcqzmnv3wxdh4rrgdwxpc47qgs3xej
    - &laptop age1hl0hkstkuu292skpuxc0kh49sm9lajg4ugns8zez000hdgfs0ausmv326a
    - &server age1jeswmcpv7k5hn2xdy89wgwqmph0yd5yv60ahyjpklch7t0zjp43szl8v8r

  - &users
    - &laptop_nikodem age13nrwdpkx23up6dre09mv5lh9lv3xynqf96sn3qlgykjmu6dzk44shvlh9n
    - &LP-043_nm1 age1eg6f0ajlmpnfxd9hfvc8j0jup2hsjfhv78wvpr898r97cmny756s2eadg3

creation_rules:
  - path_regex: host/yenn/.+$
    key_groups:
    - age:
      - *super
      - *laptop
      - *laptop_nikodem

  - path_regex: host/triss/.+$
    key_groups:
    - age:
      - *super
      - *server
      - *laptop_nikodem

  - path_regex: host/desktop/.+$
    key_groups:
    - age:
      - *super
      - *desktop
      - *laptop_nikodem

  - path_regex: home/nm1/.+$
    key_groups:
    - age:
      - *super
      - *LP-043_nm1
