keys:
  - &hosts
    - &desktop age14lex0cntf4svu3j5j6fe95sh3dlqgcqzmnv3wxdh4rrgdwxpc47qgs3xej
    - &laptop age1hl0hkstkuu292skpuxc0kh49sm9lajg4ugns8zez000hdgfs0ausmv326a
    - &softnet age1ulsnsuz6e5l8qwy9mtwwauyvfk80uw6qnwzwefd8p659e0ap9phqnluwgc

  - &users
    - &desktop_nikodem age1944c7z4v3un2j6lxhym88pc48rayhgtd70vxephnt979hdp3cdqsgqwn73
    - &laptop_nikodem age13nrwdpkx23up6dre09mv5lh9lv3xynqf96sn3qlgykjmu6dzk44shvlh9n
    - &softnet_softnet age1eg6f0ajlmpnfxd9hfvc8j0jup2hsjfhv78wvpr898r97cmny756s2eadg3

creation_rules:
  - path_regex: host/desktop/secrets.ya?ml$
    key_groups:
    - age:
      - *desktop
      - *desktop_nikodem

  - path_regex: host/laptop/secrets.ya?ml$
    key_groups:
    - age:
      - *laptop
      - *laptop_nikodem

  - path_regex: host/softnet/secrets.ya?ml$
    key_groups:
    - age:
      - *softnet
      - *softnet_softnet
