keys:
  - &hosts
    - &laptop age1afk6705wjrn0m7wzu06wvyhed765cctncz2el6fcy9nap50vfvaspcppqp
    - &desktop age14lex0cntf4svu3j5j6fe95sh3dlqgcqzmnv3wxdh4rrgdwxpc47qgs3xej
  - &users
    - &laptop_nikodem age1a4nt9mlgxf6u9z4kaj7cy6j4l4mf642d5zzn20geta0fw6808pxs85s6fh
    - &desktop_nikodem age1944c7z4v3un2j6lxhym88pc48rayhgtd70vxephnt979hdp3cdqsgqwn73
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *laptop
      - *laptop_nikodem
      - *desktop
      - *desktop_nikodem
