keys:
  - &super age12ud73504ccl26mrrqncsj204cyv0k2y7tepc64qerqts8xywja0qrn8uwq

  - &hosts
    - &geralt age14lex0cntf4svu3j5j6fe95sh3dlqgcqzmnv3wxdh4rrgdwxpc47qgs3xej
    - &yenn age1vpq06e5j3w72uyvr6mrchejlga2lam3d5cqpyvf83t8hujs4qphshw2ppc
    - &triss age1jeswmcpv7k5hn2xdy89wgwqmph0yd5yv60ahyjpklch7t0zjp43szl8v8r
    - &roach age1qupprjh7hnvx4qs5tudul36catmqahfmt7t0pznrmknt886zqs3q9cvx7y

  - &users
    - &yenn_nikodem age1scg6e6lvajg70gqr5ua7uqxhk43826zs5mpkknqemzuxuqkdv9vqcvvce7
    - &LP-043_nm1 age1eg6f0ajlmpnfxd9hfvc8j0jup2hsjfhv78wvpr898r97cmny756s2eadg3

creation_rules:
  - path_regex: host/yenn/.+$
    key_groups:
    - age:
      - *super
      - *yenn
      - *yenn_nikodem

  - path_regex: host/triss/.+$
    key_groups:
    - age:
      - *super
      - *triss
      - *yenn_nikodem

  - path_regex: host/geralt/.+$
    key_groups:
    - age:
      - *super
      - *geralt
      - *yenn_nikodem

  - path_regex: host/roach/.+$
    key_groups:
    - age:
      - *super
      - *roach
      - *yenn_nikodem

  - path_regex: home/nm1/.+$
    key_groups:
    - age:
      - *super
      - *LP-043_nm1
