apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hermes-data-pvc
  namespace: hermes
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  volumeName: hermes-data-pv
