apiVersion: v1
kind: Secret
metadata:
    name: hermes-secret
    namespace: hermes
type: Opaque
stringData:
    api_server_key: ENC[AES256_GCM,data:YvY9jJpqyoKuwttdpLdLswlVpeiwQyC0vh2zKh4rcoFcdXrEGiP6ZBTQBUzhN9ogAYVpqaZfuWsSvdeLJhaJvQ==,iv:m9JpAC7wmGK1D0p0BjAHM0ToJOzv9zsQa1l1DC1rbf8=,tag:JM8hl4VO2cBdFNrR0gw+lw==,type:str]
    ssh_ed25519_priv: ENC[AES256_GCM,data:+HC4HWwDdN3psG0jGKLb5YIzyzumRTUJ+3BbgXmWDYJlLN1OwUGbcpUOoGCjWqtc+pjkYIpXzOOVwtf8hWB1d7qbZ19mPYhr8G3xj2k2zulBJmlixx2VpCwwLFE/se5ryHRRtbkXNR69Ojv5cSg/Bk6syXS9inApX8aSI/mlMBEaa6qOv3OQE2YQBtZj5ngCc205UMEYbu4wKfZhXDdLgUSWlznnsIhz6T0Vi+bTZccmfNujfoCscMdtRpk2OMVhcigWRUgfE7OecId40wrITZHBwn+cRzJOu/0HSwCz2JmILk7cPP5GLcUOCyBsff7g+CjxkJc7YF42/FAa1uUXAsS4J1DySjpDhbbk8h2vaf2OpWNoR8ZjPGVL8+ngwOBRo0hR9m3vs4MaQk5ElzYcjAJVC1ZRC2u34GGmGHfQfr/6iqCtsewJFGfttVaNJk5kdrUWfFPkjL+SfGwkX5GN39QeiAji8P9hSypV5Kn0fcpS6TaAyVq4mmiYhwKUp+TVweGg,iv:RurVWhOGfK175vXs6hU3YhxtPeaXkQmH54WvWVxb7fM=,tag:b4IHJkdgpjC3H1fR3Diquw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobzd6SkQzRzFNV2FDZ2c2
            enN3UlQxd3lub1IxMVBsM2p6TkRvdittOGpBCmpCL2tLQmtuZUp2OUlyVXRWa25y
            bXU0NldDNHhVd0dFM041eXJtT08rSUkKLS0tIHZYQnZIakVRVDQvSzFDZFhEUkRi
            ZFJ4ZXJwalNmNUFVNWtnTkw4dWJkaTAKgCi/iBRXaCcWWldon2vU9thVFWxFnnF+
            TibQ3OpIsvBnxdgC47DqrQAGZj3tjpqgktDu5PkHPElD+RHS48TsNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l58pzs8ex5e72lgpgcavaxvx7g80937cjtqkr743hdnjvy5jramsycjtp4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T20:23:34Z"
    mac: ENC[AES256_GCM,data:bTUW+HnBTH6M3nHefI0pugkoOlvvgliqc5BlagnAldAAS060yYRT3+V4B9LDSpnEYxNRcdiIN7BSrLXT/yMl+x/LVk/eyM2+5n1abvmhfrtC2f6sA0rw04BLpVJNlXEti3HftoIVtDh9s7r7KIuX/TcTybLDZ0gx0lSLXXRQpsM=,iv:QeBnpy19hBvfBWbI1e1ORkGG+a924gXuPgQw9skD9Fg=,tag:BjTEXXei7eHQbKzb+6nsiA==,type:str]
    version: 3.13.3
