apiVersion: v1
kind: Secret
metadata:
    name: hermes-secret
    namespace: hermes
type: Opaque
stringData:
    api_server_key: ENC[AES256_GCM,data:ksjMWqncTfb4g4wXQpULz9nZBMS1aDkEWpKDDymHQ5Qrhm4Xb1/R0+NKzo8Bt9XDr4dpa5uK9AX3skN48sgrbg==,iv:glTzo/3h860BkbYPDg0prHeJXC6fIQcAhUz8KYC9lCI=,tag:Qdhm3yNyHa3cMJN8nuy1TA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQitsajA1V3pUNXhNQTVE
            MkVLWExQZnRTbHdXUGRlZlVlMXNmOWEvMXpzCjZENThCMStTWnVnSHhXZU1CR0Zv
            c3J3VjlMaGNxTEZRMkVjYTN0c1d6d00KLS0tIE5iaFFBV3h2eHpMS2x5aHVGWSs5
            ZEtlWmtwQ0p5VmxNMTc0SHd4UEw4c0UK9O3busVI8YAun7htFRo4v61X2DRBeqTH
            Xy3ni0+u8oum7vkwy08/zCcPG65IAZ0gDhAtMG1TfsGN72RO3T3ZLw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l58pzs8ex5e72lgpgcavaxvx7g80937cjtqkr743hdnjvy5jramsycjtp4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T09:27:00Z"
    mac: ENC[AES256_GCM,data:wY3wmgVMOxFyN4u2RaMsfjLXWmOKBbBZHdgXS8dZRTfZQB2vqj6oJJofedBxx3S+RR8iWVys6J0Ex1MqNwQOqXZ7mIdXua6bMOaV6qByQJLdbphUFx3IlRva+lVP+RZB3TVkOwQ+NtSoppmFK5uK8h3Qr7QzUI53w53Es0219I4=,iv:oK9YuDr/f63Y12foVoMclm1bj1Bs8fhpR8asoLv8TxY=,tag:mnbp4fu9lNWGPpXST0ASUQ==,type:str]
    version: 3.13.3
