apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: velero-backups-pvc
  namespace: velero
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Ti
  volumeName: velero-backups-pv
