apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-photos-pvc
  namespace: immich
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: nfs
  resources:
    requests:
      storage: 200Gi
  volumeName: immich-photos-pv

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-data-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-zfs
  resources:
    requests:
      storage: 10Gi
  volumeName: immich-data-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-ml-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-zfs
  resources:
    requests:
      storage: 5Gi
  volumeName: immich-ml-pv
