apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-server
  namespace: vllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm-server
  template:
    metadata:
      labels:
        app: vllm-server
    spec:
      nodeSelector:
        kubernetes.io/hostname: triss
      volumes:
      - name: models
        persistentVolumeClaim:
          claimName: vllm-models-pvc
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: "16Gi"
      containers:
      - name: vllm
        image: public.ecr.aws/q9t5s3a7/vllm-arm64-cpu-release-repo:latest
        command: ["/bin/sh", "-c"]
        args: [
          "vllm serve Qwen/Qwen2.5-1.5B-Instruct --gpu-memory-utilization 0.70 --disable-custom-all-reduce"
        ]
        env:
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-token-secret
              key: token
        - name: NCCL_P2P_DISABLE
          value: 1
        resources:
          limits:
            cpu: "2"
            memory: "16Gi"
          requests:
            cpu: "1"
            memory: "8Gi"
        ports:
          - containerPort: 8000
        volumeMounts:
          - name: models
            mountPath: /root/.cache/huggingface
          - name: shm
            mountPath: /dev/shm
