apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-models-pvc
  namespace: vllm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
  volumeName: vllm-models-pv
