apiVersion: v1
kind: Secret
metadata:
    name: hf-token-secret
    namespace: vllm
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:wDkq+MHOwd47J2P79gWsAZpU7udB7Q6SBRxjH//h2K5lJZFyJw==,iv:pNJw97bw2I8YR8ib06+QfRzSmID1RBbTmFGSEYlF0JA=,tag:XplgiPu0xFz3vj8AZXoF+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZDBraVo4Tmozd3NFVm5I
            S1FaODU3OGJrUUgzK09lR2FsRnhaOHExVkc0CmJqbUdiT0NGZE0wY2grYVpkT2hj
            K1h5Qmh0U0dUSWFYVjVTdUJ3VVVOK3cKLS0tIEhvTDFwU2tPMVZzejZ2WVJFcEk3
            TElXeFNKM1hCdkk0aG0rV2tMejFrcmMKeF8Vc2pio52ZCOVTAl6Sct6sEh+jPPdB
            qFGjGuSwNWKRpv3uTF+kjqVQqE1N+o8Qq8X2W9u/h1lMlL3dxoQ76Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l58pzs8ex5e72lgpgcavaxvx7g80937cjtqkr743hdnjvy5jramsycjtp4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T13:28:54Z"
    mac: ENC[AES256_GCM,data:lGaDom+X++bCNVBxCBIc8dtIFchhWgk7Rzu4FMgzXWdZA1cE4Yv9hOnAVW/dEnunKwCiu9NtpfGnpENKnAU4yxrQnNdUVb1VwWn+NrwBRgcWAoOxEhqVWMWq0DTHB04q+F9iIt9fV4mgkr7UyugWkkYEO5/jzl6AAf4JdEXZABc=,iv:2JD/T+S38Iy2SRlh4+Dl9AzUG/FgMGaEM30CRfpZh2c=,tag:+HwFN2fxLcS9V/eAHnWcmw==,type:str]
    version: 3.13.3
