apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-data-pvc
  namespace: navidrome
  labels:
    recurring-job-group.longhorn.io/default: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-zfs
  resources:
    requests:
      storage: 5Gi
  volumeName: navidrome-data-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-music-pvc
  namespace: navidrome
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: nfs
  resources:
    requests:
      storage: 200Gi
  volumeName: navidrome-music-pv

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-data-openebs-mig
  namespace: navidrome
  labels:
    recurring-job-group.longhorn.io/default: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 5Gi
