---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arrstack-downloads-pvc
  namespace: arrstack
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: openebs-zfs
  resources:
    requests:
      storage: 100Gi
  volumeName: arrstack-downloads-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arrstack-config-pvc
  namespace: arrstack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-zfs
  resources:
    requests:
      storage: 10Gi
  volumeName: arrstack-config-pv
