from dataclasses import replace
from pathlib import Path

import pytest

from knowledge.entry import Entry, Source
from knowledge.index import lint, render_index, scope_order, total_usage, usage
from knowledge.scopes import DEFAULT_SCOPES_TOML, ScopesConfig, parse_scopes
from knowledge.store import Store

SOURCE = Source(
    date="2026-10-06",
    by="coder",
    project="dotfiles",
    trust="agent",
    submission="s-20261006T153201Z-a1b2c3",
    evidence="saw it",
)

BASE = Entry(
    name="x",
    description="d",
    kind="convention",
    scope="global",
    tags=(),
    confidence="medium",
    trust="agent",
    status="active",
    created="2026-10-06",
    updated="2026-10-06",
    last_verified="2026-10-06",
    verify=None,
    related=(),
    sources=(SOURCE,),
    body="Body.",
)


def make(scope: str, name: str, description: str, **changes: object) -> Entry:
    return replace(BASE, scope=scope, name=name, description=description, **changes)


@pytest.fixture
def cfg() -> ScopesConfig:
    return parse_scopes(DEFAULT_SCOPES_TOML)


def test_scope_order():
    scopes = ["projects/a/facts", "org/acme", "topic/jj", "lang/python", "global", "lang/go"]
    assert sorted(scopes, key=scope_order) == [
        "global",
        "lang/go",
        "lang/python",
        "topic/jj",
        "org/acme",
        "projects/a/facts",
    ]


GOLDEN = """\
# Knowledge index

Generated by `knowledge index`; do not edit.

Total: 6/300 entries, 7.6/1024.0 KB

## global (1/40, 1.0/64.0 KB)

- [prefer-jj](global/prefer-jj.md) - Prefer jj over git (preference, high, user)

## lang/typescript (2/40, 1.5/64.0 KB)

- [no-enums](lang/typescript/no-enums.md) - Use string unions, not enums (convention, medium)
- [old-api](lang/typescript/old-api.md) - Legacy API quirk (gotcha, low, disputed, stale)

## topic/jj (1/30, 3.0/48.0 KB)

- [absorb](topic/jj/absorb.md) - absorb needs --into (gotcha, medium, disputed)

## org/acme (1/80, 2.0/384.0 KB)

- [playbook-db](org/acme/playbook-db.md) - Database playbook (reference, high)

## projects/dotfiles/facts (1/25, 0.1/48.0 KB)

- [layout](projects/dotfiles/facts/layout.md) - Where the modules live (fact, high)
"""


def sample() -> list[Entry]:
    return [
        make("topic/jj", "absorb", "absorb needs --into", kind="gotcha", status="disputed"),
        make("org/acme", "playbook-db", "Database playbook", kind="reference", confidence="high"),
        make("lang/typescript", "old-api", "Legacy API quirk", kind="gotcha", confidence="low", status="disputed"),
        make("global", "prefer-jj", "Prefer jj over git", kind="preference", confidence="high", trust="user"),
        make("lang/typescript", "no-enums", "Use string unions, not enums"),
        make("projects/dotfiles/facts", "layout", "Where the modules live", kind="fact", confidence="high"),
    ]


SIZES = {
    "global/prefer-jj.md": 1024,
    "lang/typescript/no-enums.md": 1024,
    "lang/typescript/old-api.md": 512,
    "topic/jj/absorb.md": 3072,
    "org/acme/playbook-db.md": 2048,
    "projects/dotfiles/facts/layout.md": 100,
}


def test_render_index_golden(cfg: ScopesConfig):
    text = render_index(sample(), cfg, {"lang/typescript/old-api.md": ["stale", "disputed"]}, SIZES)
    assert text == GOLDEN


def test_render_index_does_not_depend_on_input_order(cfg: ScopesConfig):
    flags = {"lang/typescript/old-api.md": ["stale"]}
    assert render_index(list(reversed(sample())), cfg, flags, SIZES) == render_index(sample(), cfg, flags, SIZES)


def test_render_index_without_sizes_uses_the_rendered_size(cfg: ScopesConfig):
    text = render_index(sample()[:1], cfg)
    assert text.startswith("# Knowledge index\n")
    assert "## topic/jj (1/30, " in text
    assert text.endswith("(gotcha, medium, disputed)\n")


def test_render_empty_index(cfg: ScopesConfig):
    assert render_index([], cfg) == (
        "# Knowledge index\n\nGenerated by `knowledge index`; do not edit.\n\n"
        "Total: 0/300 entries, 0.0/1024.0 KB\n\n(no entries yet)\n"
    )


def test_usage_rows_and_total(cfg: ScopesConfig):
    rows = usage(sample(), cfg, SIZES)
    assert [r.scope for r in rows] == [
        "global",
        "lang/typescript",
        "topic/jj",
        "org/acme",
        "projects/dotfiles/facts",
    ]
    ts = rows[1]
    assert (ts.count, ts.size, ts.max_count, ts.max_size) == (2, 1536, 40, 65536)
    total = total_usage(sample(), cfg, SIZES)
    assert (total.count, total.size, total.max_count, total.max_size) == (6, 7780, 300, 1048576)


def write(store: Store, entry: Entry) -> None:
    store.write(entry)


def test_lint_clean_store(memory_repo: Path):
    store = Store(memory_repo)
    write(store, make("global", "a", "A"))
    write(store, make("global", "b", "B", related=("global/a.md",)))
    assert lint(store) == []


def test_lint_reports_unreadable_entries_and_broken_related(memory_repo: Path):
    store = Store(memory_repo)
    write(store, make("global", "b", "B", related=("global/gone.md",)))
    (memory_repo / "global" / "bad.md").write_text("no frontmatter\n")
    problems = lint(store)
    assert len(problems) == 2
    assert any(p.startswith("global/bad.md: ") for p in problems)
    assert "global/b.md: related entry global/gone.md does not exist" in problems


def test_lint_reports_budget_overflow(memory_repo: Path):
    (memory_repo / "SCOPES.toml").write_text("[budget]\nglobal = [1, 65536]\ntotal = [5, 100]\n")
    store = Store(memory_repo)
    write(store, make("global", "a", "A"))
    write(store, make("global", "b", "B"))
    problems = lint(store)
    assert "global: 2 entries exceed the budget of 1" in problems
    assert any(p.startswith("total: ") and "bytes exceed the budget of 100" in p for p in problems)
    assert not any("entries exceed the budget of 5" in p for p in problems)


def test_lint_reports_an_invalid_scopes_file(memory_repo: Path):
    (memory_repo / "SCOPES.toml").write_text("[budget]\nglobal = 3\n")
    problems = lint(Store(memory_repo))
    assert len(problems) == 1
    assert problems[0].startswith("SCOPES.toml: ")
