apiVersion: v1
kind: Secret
metadata:
    name: secrets
    namespace: arrstack
type: Opaque
stringData:
    qbittorrent_authkey: ENC[AES256_GCM,data:INv/aF4oBIx0Bs3UtmK4H4rYKIdyzlkLIDzRd//V7ALGhRpDoBmjT6/OuZtTsRLLeUp4ZNrTQxeNRxPm2w==,iv:FWIH3Ged0Cd5Ls9t3y+xrX+FZu9//di9CNoSUptTv+c=,tag:zMdVd4qDuojFGSmrG0qffw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NWxiOVg4VHFKdUxQTldS
            VHE1YitJVTY5Q1VEVExNeTBZaUVsR21ITkg4CnhhcWVOSTZYVmw4Vm8zZ0FLTUZS
            VFZDeVdUamx3RjBpS1cweWNHeTVDK28KLS0tIGNkNTU5QVI0M01FRUpFdTBCNk56
            bHJMSHhOMVhxeStnbkNmQzl2SUprSHMKXtCMz0k4FyWFp8I/95kjiaoqS70gjPmv
            SvU8m1uy0rvKfvKLAMEA9K6coUPh0lf2kaB1t2HYsDRZbfEZHit5Bg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l58pzs8ex5e72lgpgcavaxvx7g80937cjtqkr743hdnjvy5jramsycjtp4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T20:10:52Z"
    mac: ENC[AES256_GCM,data:HrFFJiDDg/iYQgh+EhcucwkKTBpUhaEksK9YXIQ6ZmUE3Oyk926J2x3K79FTMXR5RxCZYqgdoL/8FWBapdn1sWxLtjbY+QReqqTtNTguQIF+xHGjL2D14NFJzFle6fCSF7SNupMg/JqEs1rMgVhgH4pxdnSmi2SILadvVgxP3ts=,iv:/lBf/d76SvynDktnI8DymBWMm87S/ReL2KBfepv3s/U=,tag:FWw7IJX9jFaY/ROoVMyPNA==,type:str]
    version: 3.13.3
