apiVersion: v1
kind: Secret
metadata:
    name: secrets
    namespace: cloudflare
type: Opaque
stringData:
    credentials_json: ENC[AES256_GCM,data:8pMQZL6/1NU7S5zwQ1sQBlFpDUkxuD4hfLxNUkY3M3Ha9eKogUvqhiuia1pzvHGo3o5KsC7WdcO93uH7WmafldNmpPfRdU6GaM2WMFall5qHrVAeCqQvuYknHQ495qRmZVgBLD3ejWXQY7NJhfPbm3QeiLS/iDjt1GFnrhX23x8OAVfK883sDBiVL3UYY5kFFzBfNOqMAdUTAiPFWaYC/buW9N4QsHIIic+3lsOT1Q==,iv:/3HtTvZM3KVdn94LbH8fKtxAmNHhnUu8iy/NwLkqaRM=,tag:595QRndfSrnYKohqrXQinQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcHpyVEtTY2FoMkdjSXg3
            eUtIR2QvM2VUQlRkK0I0T0F3amZhWE10d0VjCisza0xQRmdhV2xKWklrd1VyY0c5
            NERrUlhia2hkNnJmR05YN0RNL2hjcDgKLS0tIHNiakJtMEZXMitaYmVWc2RXYkZj
            R3FxK0tVaXdQNDlES1llMFV5bUlIZXMKwErrdg5JZEQ/4E/EYHjMNBCUYhdZDXYl
            YiFbekSLDvV89UvLYVlSMiyYbVxt17d/8wVAaOTMYNpiBxZlFlVlHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l58pzs8ex5e72lgpgcavaxvx7g80937cjtqkr743hdnjvy5jramsycjtp4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T20:35:40Z"
    mac: ENC[AES256_GCM,data:KUYFmUaX0++96emOSYQH60oWko434+AiJsCcibxQXpkQJvk0YqdwhcwxKZWLfHeVSnsjHAUS2ilkAzrqADPAdvXhaDcse/rKMmyNXigsZX1kR8Jf8XmPdTmyc3uyz97Q3pOvNyZQj6NZVqBn6/hUsxuzTNu1tawesR3qHS0FhiU=,iv:ZaWGx2hzTE/muSfwoHnHm4AidoJG5mnl8htGavPY3f8=,tag:aSunGOtpqBIkntQlDR1p1g==,type:str]
    version: 3.13.3
