apiVersion: v1
kind: Secret
metadata:
    name: secrets
    namespace: hermes
type: Opaque
stringData:
    api_server_key: ENC[AES256_GCM,data:nGKjG64oGG2QxK3T7vhLbOLkgUgo0/Q/YR3JoPw1Q3g+Xhhg5D9xFOj5/YcUC5qSX5vGWo9JogWiJqlKqGyoSw==,iv:QTFaNGigjq6EpQiZ35Dw+UJh80T4+rWZlmvmQ3gkQEE=,tag:Om3QBn5TqZmhgcp/jPQGlw==,type:str]
    ssh_ed25519_priv: ENC[AES256_GCM,data:zacdUBFjGM7BLR8hfuFMxxehMRRTRKq/NCg5UN70Xy8q54zP6DT5N13iFq/pe2bvLbWCT+A+ItXHHYBIEEpOQ5j9t8djIE4LgDfFNDbKltS1dbt6VCKCBGc63ZVPbyQr/zYRrYdU3VVKUfWm0v8C68qSVJ7dl7bgUheiX5uZaGSN9JTDXlMPl29YsspLOr1EK1u0/SiLbLG+P9j67TFAfRACHDZfeEf6j4FczJKcg3Q0zTU+IjzbJqY+v9Qk+9NOrFxapZV4/QtC4Q9H1seSapS7kEEPDpreFsIH+CpgBQWZ6l/gyU7SsuBKjAwMmKxxlrgrN/cYiB4WnBnmf+rOOltVxzL2aNQs6zPAV7pxw1oRHIal4xLm8o/BabbeI3O+WbjxxA7Ts/ijxCuK7oU9fCH0PNFkFwFmEn+GGEmO4N9qqocxFxyfm9Wuq1hmfev8TbfM1bB6QlrDO9j+Qz1pGTspxrNLvlxi7hE/rJN/ZHAin5x8il1NonEW/wZQj3Zn5uu+,iv:rYvTcIv8fSe3CQfLyTcOuCRTMpsx61ZQ27gCYXmZ1s4=,tag:fnpTEyCy5VPstxiK+FU4pw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3d2hGK2R0dUJIekNnNFZ5
            blZJNEFQYWVvaVp5OVY1SVJBY1V4WXltakY4CjVmMjRqQTF2NVFpcXJ6Vmp3VTZO
            RmlCUzRIUmpxdFJvZGdGME0vQ0c0cmMKLS0tIEszR0pOVndWTzhiV2czTnU3czRq
            YnFaS3dWM3JqeHR2OTQwTlNDbGZQbDQKHwtPdBssInXIxNT4cPjam1pIUeVwvUkL
            r+Pal0MBywydI+SMCLSAvF48N91IVNaS2YG/DCfiiVuOv7ncVvVxZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l58pzs8ex5e72lgpgcavaxvx7g80937cjtqkr743hdnjvy5jramsycjtp4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T20:11:02Z"
    mac: ENC[AES256_GCM,data:XEIvjizjTMEPMGw8ZPJu6l7OFhG7AnHYkbzRZIKCEZHHY/vqytqF7ZQKXBTGY647yMdPE4ofQBNJAmFXq+/DBfTEiu8JfdEhm0zwbQ/CkHnoEdLYlfEqRn6Gm5p3VnqgiIosL83qWZFd7jUJ8OpwplV3QijHFfG7/dLHNj8utwg=,iv:zLf0R/muzJRKIVFscekSjhCMm5Rz+JSBxu+Zw+8o6xE=,tag:oe+0artRZOSXXC6hpExj0A==,type:str]
    version: 3.13.3
