apiVersion: v1
kind: Secret
metadata:
    name: secrets
    namespace: navidrome
type: Opaque
stringData:
    audiomuse_navidrome_password: ENC[AES256_GCM,data:THiq9XYogHby3i0SfCDB6Up92Mk=,iv:9YmNxNfOX2kvP4jhAermWZ3GngyxBqszFph+Wy2JY98=,tag:pLtPcEe/Yg5hy9fke60NEg==,type:str]
    audiomuse_navidrome_user: ENC[AES256_GCM,data:9o4TllY=,iv:R2vOqKRXxzN7VWIIqjOJF8SbexO2pUvdVUBKsTHkpjk=,tag:HfVXEx/+b9F/j1OcA47llQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Q3o0Uzg0STk1bkhueVNz
            Ynd2azJxRkFYcDNvMUdkSnA0c1FxNUtiaHljClpFZm8yYjJiK3dRKzF0elkweGNM
            M09CQmdnMVRQbm85aHRCRUxjbmJWTDAKLS0tIE0yRjZkakVLampyOFFmbjN0WGYr
            UkI3V0I5QkVNeTZPayt4RVVSZ2J3WUkKvrz23q5XXsHsgqVTPBsPPitUNZmxkCn1
            1fpxjkZ+0+ANqrhLOIxW9YfZxV4SxaQDPQ868G5+EcRz3gSbYsOd1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l58pzs8ex5e72lgpgcavaxvx7g80937cjtqkr743hdnjvy5jramsycjtp4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T20:35:51Z"
    mac: ENC[AES256_GCM,data:megSVtDY2U2hUx8FaAbKWSI7llzXhg4x7EFtxkzyM/FSbAkDMQj6aRzjZxQ/9AVBn5ve0DkKMMz3Sh21xXHHmmG4F69LiNv7qv7UJPR4wab7k546sZIEWcSfa00u3Unzm11QW9qd2uEGBAjS0Z38IkbFXcEd5fHPOgu8d7D1dlM=,iv:PyE1etW7ickbKVj2Ut4LxLwt6Zk6rM+hSn5TW6t/GxQ=,tag:BTQsQiPfH0F2HaMwine/eg==,type:str]
    version: 3.13.3
