apiVersion: v1
kind: Secret
metadata:
    name: secrets
    namespace: omniverse
type: Opaque
stringData:
    git_token: ENC[AES256_GCM,data:b833fIFUROYUmrQcf+t7EmY+Ix7DdDmbUehBNyAEM61oQOBmclK3r/vsccPhMRzyl/a6LV4+FyT/4hxzgPY4Cdqc7aEHi0JfUda5RIlWrhYV0vGewrhOnk4/A71A,iv:w1DPGB9sGsCunb3gtWpma0GwnDCHGlnuMLszPM3DA2I=,tag:fphEaqkskH12/Z5H8yK4bA==,type:str]
    git_username: ENC[AES256_GCM,data:6x44tLye7auxNZmI,iv:fJiRMNX4khxF7miBRjLln/ESbpdctPTOkugVbDAvCjY=,tag:52TNoMI6tAm4d/I27mv5GA==,type:str]
    webdav_password: ENC[AES256_GCM,data:DuIjLYy2O+hYn+ZQ7DYEq0gPhSk=,iv:Z3Apaph4ZFXt3Mz7xSBlmp9qRvCZSMuogW0Y7s4zfIQ=,tag:lo+jtR3cE2Ia669AADCxaQ==,type:str]
    webdav_user: ENC[AES256_GCM,data:TCQ1BWcPFbBg,iv:2ypiwp5q+D+oFPoMlC2zcDhYdkcqvbcqLGIVfT2tv4o=,tag:Md8z1RO1xdBF/GUGOaoGAw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Tm55S0E2N0g1dHFZRit5
            TlVueTJML3BsaEhSNFlFREl3SzV6cUYrRW53Ck5SckFycWlyK2NBTzcvaWxKQ1lJ
            T3I3TEpyUHJjaDNQL1VVaDB1b3lBcjgKLS0tIFpnWkhnemJkRGsxNlc1WHY0QW1n
            VnI2WS9Tc3dJV1hqODdIaEJsdnBGK00KOqHW5Tdxy65MgC4S8HYbaEfzlDsnkN8b
            vSTM/Ke1H4zutKk8vJxvXfrgSkPm24/GJLySDV7C/9NTsqNeYIMR0g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l58pzs8ex5e72lgpgcavaxvx7g80937cjtqkr743hdnjvy5jramsycjtp4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T20:11:14Z"
    mac: ENC[AES256_GCM,data:mlinJD3UW7eT8LfGI3IcqHQGlRZ62aKy/eyUfsLhogN9Err0rsAera5nCQGh2gid7Fcs5mKilxvOaUDGPeVH0F2ArvIN0nyHJL3FeioGhHJF5C+/qfk47sWOJXX2oxm9YynVCemqZm9SddqyHIS5XU1E1ik2CuPeihP+gyhqF84=,iv:6WmoEXjZuRHAckJWRJpYY1UHMrp3pMO9CRnuexFY2vM=,tag:5uXto9TK6b2h/Okfg8q32w==,type:str]
    version: 3.13.3
