apiVersion: v1
kind: Secret
metadata:
    name: secrets
    namespace: shani
type: Opaque
stringData:
    host_ssh_ed25519_priv: ENC[AES256_GCM,data:p8CRNLWXhs2He3OykiH75H4yJUz67bLBZA6BEDHjqzdgglaT1g7eatDb2h5OWWsjIgwDXPE9IbzEKzYXgZjVgJ/5ClPpDMS/GQ1f/ys45Q0OmovLPw70oFJrXNKhj7rwnzqkbozoKy65e5sjgdMwe4u8vhSY62SBFONh1U/Dd8XD9qA5C5QbM8dQwkbSWo6DgOybjf34TaCYpeZw1D9DYurFRv8JE31kvXhAC3mjPbmm9EfSxUn/aoCmqPR3cSZyHsozdv7H0vWfvjuYAXpAUZNqa266bQzK8iAu2jA1xGP4L6D3ao0JYnQlycjpcCrfouCoS0Go23CwePuhKxkJY3kRt/buzEp+QF+xybCPz3AxmBRLnIjpRjT1xhW3G51Mq+zwZsx4eTHfy/60x7DbENzHX7u4udvpZ/IpLEXqjZ4fXKUCxzRIAh0uhvEqQjm1JQpDaOC5dDkYRAlN9x17fjKqli8BgD3UReJZ3gqdv7gbT1+NUKsVTZMjLeqkqn/5rp+j,iv:B29ypWOm5Se43hudVmnMXnjccIglGq2NoMRpqGN6s+0=,tag:PI8KRMHppdtqMyk6hxpjtg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdnpXVzY0cDJxUEFOWkZW
            emNLN0h5WE9hSWY0SkF1dkthK3c5MjJtbTJNCk5HM0FhR2k5dHVVZEtuT1BkTExa
            eDJwa1JMakxtRjhuOUtDOGFmTHkvVVkKLS0tIHdQNE1jUnZNZTY4NURBZHdHTm9B
            NW1vaTlKUHFHN1BaT2ZyS0tZSU51clUKbLPJmbzo5KKJACWqXLBrsgd+E/3vWL32
            K1HjvSUrV0aKLAugYwKsqN0vEpwWb5c+CGhm6watZQdkSSi3IcQLlg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l58pzs8ex5e72lgpgcavaxvx7g80937cjtqkr743hdnjvy5jramsycjtp4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T20:11:19Z"
    mac: ENC[AES256_GCM,data:2OvLOYHxKxSYwsDW42pWcmzkpmqFXKsXTN8TX14s5Zciv4+mdWYxUVhYZX6n/W1ihw8LOw65gUrrmKYPj06kAnuZ2a30wm87BB6c3Cu4qfClKN1OyVKBik6kkKvAQlYg5dje2Cvdv5xapwg8ELQ1Iuov/TFxK95inEjH6aAhmwk=,iv:JSEooIPX+iY1IiZW4pDKTufvyUnr+rMP5OeVGQpkMdY=,tag:4IbcorAo/fqZRWIe/MAmiA==,type:str]
    version: 3.13.3
