apiVersion: v1
kind: Secret
metadata:
    name: secrets
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:nR2eWpZDw3c/7Jyc7fzNiVEy,iv:feg9seWj6zocScB7GNy078li3YEMcmSJEQ3yWbeaIOI=,tag:8Q56XH0PYG4mD+zoptItAQ==,type:str]
    client_secret: ENC[AES256_GCM,data:WD1oG/7AikswcUi7uy2cfuSsR57M02Iokjjl2DqegiFCUolhrfSo+LilBjiiQzkKGZ/BuIh77dNxqHyy96352A==,iv:Ul43OmPHyyPSsVS1tsPahxqrmQX5fBi6ig18V3lmnFI=,tag:z1BiZbiRbttDXOPldlvoDA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UnpXNmRHaEl5dmhDOFdP
            VEZ4dUF2ZWdFV2kvZmUzdm5GeHd6MXhrNUMwCklpd0pvRmJvRENYMG85SkJzdDhy
            a1R0TEZiRm03ZU9vWk9Za3RTNDV5SzgKLS0tIFBpSGttbnRZQk82dWVxWTdiMmtH
            dkNnNDE5K3VINFF0aVJ5YnU5VDk0Y00KES78xmNvhw7+GKeH4tdy95cTFGfOKq0a
            e/kjGYmhwDU4R9ZvOcs5ayHgs1CeJFgQOEYlJ9sySr3EE8gYFm1IQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l58pzs8ex5e72lgpgcavaxvx7g80937cjtqkr743hdnjvy5jramsycjtp4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T20:11:24Z"
    mac: ENC[AES256_GCM,data:tCiCCEMQ3IDvDl3DfvbEH6TQMzliezwPsa8b5Spc5PJQBUTckgyw06rnjJmSUF2zR6jJo3o/QvbL6BacuNpSdaGlruJU8KAYQzWGa2ohgWKW8R4PAx7NXpKz8zC4oC10zqxpGyV5WpkfsGu+ggSao2qlFEQdqf0LyIbjIS54Xs4=,iv:BSxg12PjzVpRs+poTKOfh1DQJW8ZG0iiNLNtXwOGXPc=,tag:wV/iOdBqISjJAvmhTKQFMA==,type:str]
    version: 3.13.3
