apiVersion: v1
kind: Secret
metadata:
    name: secrets
    namespace: webdav
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:nuS76gSXXoGnt4YsI42jMmC0eR8=,iv:yo7jmbz6i3W7iAl8Oo2aukb0TWeWk8cPdggohO2eWHA=,tag:uuMhEODLKy/kYUonkQGWMA==,type:str]
    user: ENC[AES256_GCM,data:gSY3Bzk=,iv:5ktWYj4vvDalFlOjSBBXYN7+l5YTIWLRFB551pq22M4=,tag:uh32BNtRjpdkuFRdVpLsNQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNXFqd25zOWdwOHIyQmFV
            RHRyN1lhL3pxbG01TXZ1NGt4YkdUWjZsMGlvCko4d3dwS3VqUGN5Q0ZNYkR5WG1Z
            VlBMZ0ZEMHovR3B3MXhSV2pialZiaE0KLS0tIG9xTGpCV3hRdS9EVVNzSWYzRU1p
            Q3FROENORVJqMnNwNE9EUnNOcTBRa28KC5myvjc+VyMnQ48beg2IR5oGhYvWzKnE
            2rEcNKGrfvQ+3UQOArSDAvq4zarNSDMak4pm3txTsF20BO6wsX+SNw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l58pzs8ex5e72lgpgcavaxvx7g80937cjtqkr743hdnjvy5jramsycjtp4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T20:11:30Z"
    mac: ENC[AES256_GCM,data:ySBGmv/SU1K1BC50NGt4H1lJJNDd5dqvSG19hqr3dHwScA4qWyarL5IBMxdQ3tHrWBVImqHHDVs9IapgKvtR/jzXogB9LJSX+4hNSz/XltN/HVNu3ryDdg+/gmkYX7vgPA1xARep0D8atNu7DcHKsaUVWopb0DvqEondmnLoyJE=,iv:Y76Zwul0RcF8WP7vvN6L0AsjcdZngoBywu90aHOaV0Y=,tag:hsoBtDZarYoPhCIHwQ9rPw==,type:str]
    version: 3.13.3
