apiVersion: v1
kind: Service
metadata:
  name: arrstack-interceptor
  namespace: keda
spec:
  selector:
    app.kubernetes.io/component: interceptor
    app.kubernetes.io/name: http-add-on
    app.kubernetes.io/instance: keda-add-ons-http
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: proxy
    - name: flaresolverr
      protocol: TCP
      port: 8191
      targetPort: proxy
---
apiVersion: v1
kind: Service
metadata:
  name: ts-bazarr
  namespace: keda
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "bazarr"
spec:
  selector:
    app.kubernetes.io/component: interceptor
    app.kubernetes.io/name: http-add-on
    app.kubernetes.io/instance: keda-add-ons-http
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: proxy
---
apiVersion: v1
kind: Service
metadata:
  name: ts-prowlarr
  namespace: keda
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "prowlarr"
spec:
  selector:
    app.kubernetes.io/component: interceptor
    app.kubernetes.io/name: http-add-on
    app.kubernetes.io/instance: keda-add-ons-http
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: proxy
