#! /bin/sh

setxkbmap -layout pl,us -option caps:escape &
pgrep -x sxhkd > /dev/null || sxhkd

bspc monitor DisplayPort-2 -d 1 2 3 4 5 6 7 8 9 0 a

bspc config border_width          2
bspc config window_gap            5
bspc config border_radius         8

bspc config split_ratio           0.5

# colors
bspc config normal_border_color   "#353F67"
bspc config active_border_color   "#61FEF4"
bspc config focused_border_color  "#7FDF64"

# rules
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_eDP1)
bspc rule -a Opera "desktop=a" "state=fullscreen" "follow=off"

# init
$HOME/.config/polybar/launch.sh
feh --bg-scale $HOME/pictures/wallpapers/neon-city.png
picom --config $HOME/.config/picom/picom.conf

opera
