#! /bin/sh

setxkbmap -layout pl,us -option caps:escape &
pgrep -x sxhkd > /dev/null || sxhkd

#bspc monitor eDP1 -d 1 2 3 4 5
#bspc monitor HDMI1 -d 6 7 8 9 0
bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width          2
bspc config window_gap            5
bspc config border_radius         8

bspc config split_ratio           0.5

# colors
bspc config normal_border_color   "#353F67"
bspc config active_border_color   "#61FEF4"
bspc config focused_border_color  "#7FDF64"

#polybar hidden when fullscreen for vlc, youtube, mpv ...
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_eDP1)

$HOME/.config/polybar/launch.sh
feh --bg-scale $HOME/pictures/wallpapers/neon-city.png
picom --config $HOME/.config/picom/picom.conf
