apiVersion: v1
kind: Secret
metadata:
    name: shani-secret
    namespace: shani
type: Opaque
stringData:
    host_ssh_ed25519_priv: ENC[AES256_GCM,data:UX+KSUWhXmqjpt6Rr3TTP9ijreyhZc0BhVZ+YoomrFEh90Iyf0HNo/d2MEHHZQD0uatbTAJibGlbC7M9GiizzFdQNtfquubL82QD3hjaSUTAKirIShs8HlBiOowT5zSjcxSBsHgIzvTqAp15rMr8VKmfSIncWFjmG1rvW0BdNVZ9aSnZ7yHqw8zNmU/PwNAPWFkM9h47uukV05xzmrl20d9p8ba4RbVjVxOSuZmwFtDK7M2xf9/HjDiki/bMk2xRQgko19mrQxeH1jGCEmeItV23f0beK+MwyWWyqrzM1i1F0XbqXdKVUBxNoJFQvYiNx/JW21L8QkcEfJ/yd4Jb9uKJrv/SBdbYZGxYZYr8cxtlOq2as+j4oYyfHVSZTaJiD7aStf+YrYUa9xl6KtW2eI4JJtZIX/5jjdUPk3Ys+wmUMaPAQPiKefvl8rtGl8gOPaf3ziR7gR/XyBelBuxeeS39OGRPdNIM22/NoZ05gHze/kyPNu/zaNeRnUyyck9AClrd,iv:tt6vneeATgp+Esk67G/ugFaTLR/lEjxfZunIBVuTiHc=,tag:/3wdqVCpm+0MaR+aHYNh2g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaOGJWOEtPWWhMRnZjdkQr
            cVJBL21naEJueWc3aDI3MmR6bUp1aGJNNno0CndlbFFJazFTTnQ5STZ6YXdDeExG
            K3FPQlJ6b2hvYThNSkFOS05BZHJNOTQKLS0tIERxcC9yczM3ZTNiTHBMalNLSVpS
            c04zcmJUMGVPVVF1UkpiaWQ1MWxzNHcKmDasG/HukHdQfJe3OnCZYqR0fuda/Lx1
            o6Hv0f1WlEoYTJVw9odPtD/LhNAAyyOhtb5zNt+XadnaDKkQjEK1+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l58pzs8ex5e72lgpgcavaxvx7g80937cjtqkr743hdnjvy5jramsycjtp4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T19:05:14Z"
    mac: ENC[AES256_GCM,data:ofksGmdaJgv6I4qVFyEmiKXkKXzjkVy83g99tak/Dw5KzGkHXoi4gY4RTSIyKs9840MeNUyuVlhIBy0EjsZNIxFsXMwEgcImOIaI6foDSRO3LjJe39eB4CprFe7TF4585Bv6Ne5THnnvsQkc6QpMSu7SL3RjxChlxYfTdp4zTNI=,iv:UWOHbJBxUEAhhvEoRC60LhwkOJnUd1dpSDmTJ9mwyxg=,tag:x5jxida6j1mA8qGw2ZyRzw==,type:str]
    version: 3.13.3
