apiVersion: v1
kind: Service
metadata:
  name: shani-service
  namespace: shani
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "shani"
spec:
  type: ClusterIP
  selector:
    app: shani
  ports:
    - protocol: TCP
      port: 22
      targetPort: 2222
