#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
email = "62289991+NikodemMarek@users.noreply.github.com"
name = "NikodemMarek"

[ui]
default-command = "log"

[git]
track-default-bookmark-on-clone = false

[remotes.origin]
auto-track-bookmarks = "nm1/*"
auto-track-created-bookmarks = "*"
fetch-tags = "v*"

[snapshot]
auto-update-stale = true

[aliases]
upload = ["util", "exec", "--", "@jjUpload@"]
sync = ["util", "exec", "--", "@jjUpload@", "sync"]
stack = ["log", "-r", "stack()"]

[revset-aliases]
"stack()" = "trunk() | trunk()..(@::)"

[upload]
bookmark-prefix = "nm1/"
