apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      volumes:
        - name: models
          persistentVolumeClaim:
            claimName: ollama-models-pvc
        - name: data
          persistentVolumeClaim:
            claimName: ollama-data-pvc
      containers:
        - name: ollama
          image: ollama/ollama:latest
          ports:
            - containerPort: 11434
          env:
            - name: OLLAMA_HOST
              value: "0.0.0.0"
            - name: OLLAMA_MODELS
              value: "/models"
          volumeMounts:
            - name: models
              mountPath: /models
            - name: data
              mountPath: /root/.ollama
          resources:
            requests:
              memory: "8Gi"
              cpu: "1000m"
            limits:
              memory: "16Gi"
              cpu: "4000m"
