apiVersion: v1
kind: PersistentVolume
metadata:
   name: ollama-models-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
   server: 100.100.215.91
   path: /mnt/models
  mountOptions:
    - actimeo=300
    - noatime
    - nodiratime

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-local-models-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: openebs-hostpath
  local:
    path: /var/openebs/local/ollama-local-models-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - triss
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-data-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: openebs-hostpath
  local:
    path: /var/openebs/local/ollama-data-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - triss
