apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: ollama
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "ollama"
spec:
  type: ClusterIP
  selector:
    app: ollama
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434
