apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: bazarr
  namespace: arrstack
spec:
  hosts:
    - bazarr
    - bazarr.tail5874bc.ts.net
    - bazarr.arrstack
    - bazarr.arrstack.svc
    - bazarr.arrstack.svc.cluster.local
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bazarr
    service: bazarr-app
    port: 80
  replicas:
    min: 0
    max: 1
  # Scale to zero after 30 minutes without requests.
  scaledownPeriod: 1800
  scalingMetric:
    concurrency:
      targetValue: 1
