"""KNOWLEDGE.md, the generated index of the store, and the checks behind `knowledge lint`."""

import logging
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path

from .data import ParseError
from .entry import Entry, render_entry
from .scopes import ScopesConfig, load_scopes
from .store import Store, atomic_write

log = logging.getLogger("knowledge")

INDEX_FILE = "KNOWLEDGE.md"
INDEX_MODE = 0o644

# the order of the sections: global, lang/*, topic/*, org/*, projects/*/facts
_SCOPE_RANK = {"global": 0, "lang": 1, "topic": 2, "org": 3, "projects": 4}


@dataclass(frozen=True)
class ScopeUsage:
    """What a scope (or the whole store, named `total`) holds, and what its budget allows."""

    scope: str
    count: int
    size: int  # bytes
    max_count: int
    max_size: int


def scope_order(scope: str) -> tuple[int, str]:
    return _SCOPE_RANK.get(scope.split("/", 1)[0], len(_SCOPE_RANK)), scope


def _by_rel(e: Entry) -> str:
    return e.rel


def entry_size(e: Entry, sizes: Mapping[str, int] | None) -> int:
    """The file size if the caller knows it, else the size of the entry as it is rendered."""
    if sizes is not None and e.rel in sizes:
        return sizes[e.rel]
    return len(render_entry(e).encode("utf-8"))


def file_sizes(store: Store, entries: Sequence[Entry]) -> dict[str, int]:
    """The size of each entry's file on disk, by path."""
    return {e.rel: store.bytes(e.rel) for e in entries}


def usage(entries: Sequence[Entry], cfg: ScopesConfig, sizes: Mapping[str, int] | None = None) -> list[ScopeUsage]:
    """One row per scope that has entries, in index order."""
    counts: dict[str, int] = {}
    totals: dict[str, int] = {}
    for e in entries:
        counts[e.scope] = counts.get(e.scope, 0) + 1
        totals[e.scope] = totals.get(e.scope, 0) + entry_size(e, sizes)
    rows: list[ScopeUsage] = []
    for scope in sorted(counts, key=scope_order):
        max_count, max_size = cfg.budget_for(scope)
        rows.append(ScopeUsage(scope, counts[scope], totals[scope], max_count, max_size))
    return rows


def total_usage(entries: Sequence[Entry], cfg: ScopesConfig, sizes: Mapping[str, int] | None = None) -> ScopeUsage:
    max_count, max_size = cfg.total_budget
    return ScopeUsage("total", len(entries), sum(entry_size(e, sizes) for e in entries), max_count, max_size)


def _kb(n: int) -> str:
    return f"{n / 1024:.1f}"


def _flags(e: Entry, extra: Sequence[str]) -> list[str]:
    flags: list[str] = []
    if e.trust == "user":
        flags.append("user")
    if e.status == "disputed":
        flags.append(e.status)
    flags.extend(f for f in extra if f not in flags)
    return flags


def render_index(
    entries: Sequence[Entry],
    cfg: ScopesConfig,
    flags: Mapping[str, Sequence[str]] | None = None,
    sizes: Mapping[str, int] | None = None,
) -> str:
    """The text of KNOWLEDGE.md. `flags` adds markers per entry path; `sizes` are the file sizes by path."""
    extra = flags or {}
    total = total_usage(entries, cfg, sizes)
    lines = [
        "# Knowledge index",
        "",
        "Generated by `knowledge index`; do not edit.",
        "",
        f"Total: {total.count}/{total.max_count} entries, {_kb(total.size)}/{_kb(total.max_size)} KB",
        "",
    ]
    if not entries:
        lines += ["(no entries yet)", ""]
    groups: dict[str, list[Entry]] = {}
    for e in entries:
        groups.setdefault(e.scope, []).append(e)
    for u in usage(entries, cfg, sizes):
        lines.append(f"## {u.scope} ({u.count}/{u.max_count}, {_kb(u.size)}/{_kb(u.max_size)} KB)")
        lines.append("")
        for e in sorted(groups[u.scope], key=_by_rel):
            marks = ", ".join([e.kind, e.confidence, *_flags(e, extra.get(e.rel, ()))])
            lines.append(f"- [{e.name}]({e.rel}) - {e.description} ({marks})")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def regenerate(memory: Path, flags: Mapping[str, Sequence[str]] | None = None) -> int:
    """Write KNOWLEDGE.md if its content changed; the number of entries in it. `flags`: markers per entry path."""
    store = Store(memory)
    cfg = load_scopes(memory)
    entries = store.entries()
    for rel, msg in store.errors:
        log.warning("%s: %s (left out of the index)", rel, msg)
    text = render_index(entries, cfg, flags, sizes=file_sizes(store, entries))
    path = memory / INDEX_FILE
    try:
        current: str | None = path.read_text(encoding="utf-8")
    except (FileNotFoundError, UnicodeDecodeError):
        current = None
    if current != text:
        atomic_write(path, text, INDEX_MODE)
    return len(entries)


def lint(store: Store) -> list[str]:
    """Everything wrong with the store: unreadable entries, broken `related` paths, SCOPES.toml and budget overflows."""
    entries = store.entries()
    # an entry's own error message already names its path
    problems = [msg if msg.startswith(rel) else f"{rel}: {msg}" for rel, msg in store.errors]
    known = {e.rel for e in entries}
    for e in entries:
        for related in e.related:
            if related not in known:
                problems.append(f"{e.rel}: related entry {related} does not exist")
    try:
        cfg = load_scopes(store.root)
    except ParseError as e:
        problems.append(str(e))
        return problems  # without the config there are no budgets to check
    sizes = file_sizes(store, entries)
    for u in [*usage(entries, cfg, sizes), total_usage(entries, cfg, sizes)]:
        if u.count > u.max_count:
            problems.append(f"{u.scope}: {u.count} entries exceed the budget of {u.max_count}")
        if u.size > u.max_size:
            problems.append(f"{u.scope}: {u.size} bytes exceed the budget of {u.max_size}")
    return problems
